### PR TITLE
Corrections release 1.0.0

### PR DESCRIPTION
**Pull request by jannikseidelQBiC**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

## Changes requested for release 1.0.0
- renamed output folder `blastn/filtered_ident_cov` from camelCase to snake_case
- changed naming schema in the `schema_input.json` to be more intuitive (Testdata is already updated to work with this new naming convention)
- replaced sys.exit() with raise ValueError in renaming script to make the pipeline fail loudly in such a case
- updated the changelog and set the date to 2024-03-19 and added a code name for the release
- removed `nf-test` reference from CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md for now, will be readded in the future
- set linting to ignore the removal of `nf-test` from the above mentioned files
- removed input check from `detaxizer.nf` as this would be redundant with `nf-validation`. Pipeline is now running only with correctly formatted samplesheet entries but does not fail anymore when a wrong entry is present.
- adapted new naming schema for input in `detaxizer.nf`

### CODE REVIEW

**Comment by jannikseidelQBiC** [comment]
@nf-core-bot fix linting

**Review by asp8200 — APPROVED** [review]

**Comment by asp8200** [comment]
Well done, @jannikseidelQBiC. Just I don't quite understand the following sentence from the description "Pipeline is now running only with correctly formatted samplesheet entries but does not fail anymore when a wrong entry is present". 🤔

**Comment by jannikseidelQBiC** [comment]
@asp8200 seems that nf-validation does not stop the pipeline run when a wrongly formated samplesheet is present, then the pipeline just runs empty. Do you have any knowledge if this is correct or do I have to set a parameter in the `schema_input.json`? Waiting before merging for your answer :)

**Comment by asp8200** [comment]
> @asp8200 seems that nf-validation does not stop the pipeline run when a wrongly formated samplesheet is present, then the pipeline just runs empty. Do you have any knowledge if this is correct or do I have to set a parameter in the `schema_input.json`? Waiting before merging for your answer :)

Hmmm ... I know too little about the nf-validation plugin, but I would have expected the nf-validation plugin to stop the pipeline if the samplesheet is "wrongly" formatted. Perhaps the `schema_input.json` doesn't describe precisely what is correct and what is wrong? 🤔  Did you perhaps try and compute your `shema_input.json` with the one from [sarek](https://github.com/nf-core/sarek/blob/master/assets/schema_input.json)? If you tell me more about what a wrongly formatted samplesheet is, then I can also try to do some testing and experimenting on my side :-)

**Comment by jannikseidelQBiC** [comment]
for example, if I use only `short_reads_fastq_2` or misspelling one of the labels in the header. 

``` csv
sample,short_reads_fastq_1,short_reads_fastq_2,long_reads_fastq_2
test,,https://github.com/jannikseidelQBiC/nf-core-test-datasets/raw/detaxizer/test_data/test_minigut_hg38host_R1.fastq.gz,
```
I do not think this behavior is intended, so I wait with merging till I can resolve this issue ...
Would be great if you would try experimenting a bit, maybe then a solution can be found quicker :)

**Comment by asp8200** [comment]
> for example, if I use only `short_reads_fastq_2` or misspelling one of the labels in the header.
> 
> ```
> sample,short_reads_fastq_1,short_reads_fastq_2,long_reads_fastq_2
> test,,https://github.com/jannikseidelQBiC/nf-core-test-datasets/raw/detaxizer/test_data/test_minigut_hg38host_R1.fastq.gz,
> ```
> 
> I do not think this behavior is intended, so I wait with merging till I can resolve this issue ... Would be great if you would try experimenting a bit, maybe then a solution can be found quicker :)

Ok, let's take this to the nf-core Slack channel for detaxier

**Pull request merged**
